# Generated by Django 2.2.3 on 2019-07-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20190714_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmreview',
            name='time',
            field=models.TextField(),
        ),
    ]
