# Generated by Django 2.2.3 on 2019-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20190714_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preImg',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('F', 'FilmReview'), ('T', 'Tech'), ('O', 'Other')], max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='<p>null<p>'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
