# Generated by Django 2.2.3 on 2019-07-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20190714_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='正文',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='preImg',
            new_name='预览图片',
        ),
    ]
