# Generated by Django 2.2.3 on 2019-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_auto_20190714_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='article',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次编辑'),
        ),
    ]
