# Generated by Django 2.2.3 on 2019-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20190714_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='预览图片',
            field=models.TextField(default='data:image/jpg;base64,'),
        ),
    ]
