# Generated by Django 2.2.3 on 2019-07-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_article_preview_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='<p>null</p>', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_des',
            field=models.TextField(default='<p class="my_single_des">&nbsp; &nbsp; &nbsp; &nbsp;</p>', verbose_name='简介'),
        ),
    ]
